use super::Case;

#[test]
pub fn examples_execute_in_both_profiles() {
    for (source, stdout) in [
        (
            include_str!("../../examples/alias-writes.mwy"),
            "7\n9\n9\n8\n",
        ),
        (
            include_str!("../../examples/reference-fields.mwy"),
            "7\n9\n8\n1\n",
        ),
        (
            include_str!("../../examples/mutable-carriers.mwy"),
            "empty\n7\nempty\n",
        ),
        (
            include_str!("../../examples/allocator-carriers.mwy"),
            "7\n9\n8\n",
        ),
        (
            include_str!("../../examples/tagged-allocators.mwy"),
            "empty\n7\nbounded\ncleared\n",
        ),
        (
            include_str!("../../examples/allocator-records.mwy"),
            "9\n2\nready\n",
        ),
        (
            include_str!("../../examples/mutable-allocators.mwy"),
            "7\n2\n1\n8\n",
        ),
        (
            include_str!("../../examples/allocator-bounds.mwy"),
            "7\n8\n",
        ),
        (
            include_str!("../../examples/heap-handles.mwy"),
            "false\nheap\n2\n",
        ),
        (include_str!("../../examples/hello.mwy"), "Hello, meowy!\n"),
        (
            include_str!("../../examples/exclusive-indexed-fields.mwy"),
            "index\n2\n2\n3\n",
        ),
        (
            include_str!("../../examples/exclusive-nested-elements.mwy"),
            "outer\ninner\n2\n3\n4\n",
        ),
        (
            include_str!("../../examples/exclusive-projected-elements.mwy"),
            "2\n2\n3\n",
        ),
        (
            include_str!("../../examples/exclusive-elements.mwy"),
            "index\n2\n2\n3\n",
        ),
        (
            include_str!("../../examples/exclusive-slot-fields.mwy"),
            "7\n2\n2\n3\n",
        ),
        (
            include_str!("../../examples/exclusive-slots.mwy"),
            "8\n8\nfalse\n4\n",
        ),
        (
            include_str!("../../examples/exclusive-fields.mwy"),
            "7\n2\n3\nfalse\n",
        ),
        (
            include_str!("../../examples/reference-blocks.mwy"),
            "7\nready\n8\n9\n10\n",
        ),
        (
            include_str!("../../examples/reference-returns.mwy"),
            "10\n8\n10\n11\n",
        ),
        (
            include_str!("../../examples/exclusive-functions.mwy"),
            "9\n9\n10\n5\n",
        ),
        (
            include_str!("../../examples/exclusive-references.mwy"),
            "8\n9\n10\n11\n20\n21\n",
        ),
        (include_str!("../../examples/factorial.mwy"), "3628800\n"),
        (
            include_str!("../../examples/records.mwy"),
            "Sensor 7: 24 celsius\n48\n",
        ),
        (include_str!("../../examples/loop.mwy"), "5050\n"),
        (
            include_str!("../../examples/borrow-results.mwy"),
            "11\n22\n42\ntrue\n",
        ),
        (
            include_str!("../../examples/borrow-liveness.mwy"),
            "41\n42\n7\n9\n0\n1\n2\n3\n",
        ),
        (
            include_str!("../../examples/borrowed-records.mwy"),
            "11\n44\n33\n44\nvalue\n0\n1\n2\n3\n",
        ),
        (
            include_str!("../../examples/optional-borrows.mwy"),
            "7\n8\nmissing\n8\n42\ntext\n",
        ),
        (
            include_str!("../../examples/borrow-functions.mwy"),
            "11\n22\n12\n23\n12\n24\n",
        ),
        (
            include_str!("../../examples/reborrows.mwy"),
            "true\n41\n7\n42\n8\n",
        ),
        (
            include_str!("../../examples/scope-borrows.mwy"),
            "false\n7\n8\ntrue\n9\n10\n",
        ),
        (
            include_str!("../../examples/bounded-lists.mwy"),
            "2\n3\nAda\nLin\ntrue\n0\n",
        ),
        (
            include_str!("../../examples/list-unions.mwy"),
            "20\nmeowy\n300\n2\n",
        ),
        (
            include_str!("../../examples/compound-lists.mwy"),
            "128\n-128\nfalse\n260\n",
        ),
        (
            include_str!("../../examples/element-borrows.mwy"),
            "true\nfalse\n20\n10\n30\n",
        ),
        (
            include_str!("../../examples/element-writes.mwy"),
            "10\n21\n2\n7\n9\n",
        ),
        (
            include_str!("../../examples/nested-writes.mwy"),
            "20\n11\n2\n1\n2\n99\n",
        ),
        (
            include_str!("../../examples/effectful-lists.mwy"),
            "value\n128\n1\nrow\n300\n",
        ),
        (
            include_str!("../../examples/dynamic-lists.mwy"),
            "read\n301\n2\n",
        ),
        (
            include_str!("../../examples/mutable-fields.mwy"),
            "1\n2\n3\nkept\n",
        ),
        (
            include_str!("../../examples/mixed-writes.mwy"),
            "1\n8\n2\n21\n",
        ),
        (
            include_str!("../../examples/emitted-slots.mwy"),
            "init\n1\n2\n2\n9\n",
        ),
        (
            include_str!("../../examples/emitted-borrows.mwy"),
            "1\n3\n2\n9\n7\n",
        ),
        (
            include_str!("../../examples/immutable-slots.mwy"),
            "7\n2\nready\n7\n2\n",
        ),
        (
            include_str!("../../examples/reference-slots.mwy"),
            "3\n7\n7\n3\n",
        ),
        (
            include_str!("../../examples/transitive-borrows.mwy"),
            "7\ntrue\n7\n7\n",
        ),
        (
            include_str!("../../examples/temporary-borrows.mwy"),
            "owner\n7\nfalse\n4\n9\n",
        ),
        (
            include_str!("../../examples/reference-temporaries.mwy"),
            "true\n7\nowner\n7\n3\n",
        ),
        (
            include_str!("../../examples/mutable-references.mwy"),
            "7\n9\n9\n8\n",
        ),
        (
            include_str!("../../examples/guarded-references.mwy"),
            "7\n7\n7\n9\n",
        ),
        (
            include_str!("../../examples/leave-references.mwy"),
            "11\n9\n",
        ),
        (
            include_str!("../../examples/restart-references.mwy"),
            "7\n9\n7\n",
        ),
        (
            include_str!("../../examples/transitive-restarts.mwy"),
            "7\n1\n9\n2\n7\n",
        ),
        (
            include_str!("../../examples/header-activity.mwy"),
            "empty\n7\nempty\n",
        ),
        (
            include_str!("../../examples/expired-restarts.mwy"),
            "1\n2\n3\n7\n9\n9\n",
        ),
        (
            include_str!("../../examples/references.mwy"),
            "true\nfalse\n42\nmeowy\n",
        ),
        (
            include_str!("../../examples/nullable.mwy"),
            "meowy\nnull\nmeowy\nguest\n",
        ),
    ] {
        Case::new(source).runs(stdout.as_bytes());
    }
}
