[workspace]
members = ["."]
resolver = "3"

[package]
name = "meowy"
version = "0.0.0"
edition = "2024"
rust-version = "1.98.1"
build = "build.rs"
readme = "docs/README.md"

[lib]
name = "meowy"
path = "src/lib.rs"

[[bin]]
name = "meowy"
path = "src/main.rs"

[dependencies]
pulldown-cmark = { version = "=0.13.4", default-features = false, features = ["html"] }

[profile.release]
lto = "thin"
codegen-units = 1
